from .base_rep import BaseRepresentation

import numpy as np
import matplotlib.pyplot as plt
from torch_geometric.data import Data

from ..featurization.base_feat import Featurizer


class PointCloudRepresentation(BaseRepresentation):
    """
    This class is used to generate Point Clouds from structure files. Points are defined as
    coordinates and a set of features generated by the featurizer.
    """
    def __init__(self, structure, featurizer: Featurizer, label=None):
        """
        Initializes Point Cloud representation.
        
        :param structure: path to structure
        :param featurizer: The featurizer previusly configured with the features to extract
        :type featurizer: FeaturizerS
        :param label:  dictionary using the structure name (eg: xxx.pdb) as key, and label as value
        """
        super().__init__(structure, featurizer = featurizer, label = label)
        self.features, self.coords, self.bonds, self.bonds_features = self.featurizer.process_structure(self.structure, False)


    def _compute_representation(self):
        """
        Computes the point cloud.
        """
        # Line to concatenate features
        feature_matrix = self.features
        point_cloud =  Data(pos=feature_matrix[:, 0:3], x=feature_matrix[:, 3:], y = self.label)

        return point_cloud
    

    def visualize_representation(self):
        """
        Generates a visualization of the representation.
        """
        fig = plt.figure()
        ax = fig.add_subplot(111, projection='3d')

        x, y, z = self.representation.pos[:,0], self.representation.pos[:,1], self.representation.pos[:,2]
        ax.scatter(x, y, z, c='cyan', marker='o', edgecolors='r', alpha=0.5)

        plt.show()